spring:
  datasource:
    url: jdbc:mysql://
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secretKey: ${SECRET_KEY}
  refreshExp: 604800000 # 1week
  accessExp: 6000000 # 2hour

springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0
    path: /v3/api-docs

  default-consumes-media-type: application/json
  auto-tag-classes: true
  groups:
    enabled: false

  swagger-ui:
    tags-sorter: alpha
    operationsSorter: alpha
    path: /swagger-ui/index.html