spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PW}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secretKey: ${SECRET_KEY}
  refreshExp: 604800000 # 1week
  accessExp: 6000000 # 2hour

gemini:
  api-key: ${GEMINI_API_KEY}
  grading-api-key : ${GEMINI_GRADING_API_KEY}
  api-url: https://generativelanguage.googleapis.com/v1/models/gemini-2.0-flash:generateContent
#  api-url: https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash:generateContent

resilience4j:
  ratelimiter:
    instances:
      geminiLimiter:
        limit-refresh-period: 1s
        limit-for-period: 3  # 초당 3회로 제한(필요하면 조절)
        timeout-duration: 0

  retry:
    instances:
      geminiRetry:
        max-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - org.springframework.web.client.HttpClientErrorException$TooManyRequests
        exponential-backoff-multiplier: 2

springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0
    path: /v3/api-docs

  default-consumes-media-type: application/json
  auto-tag-classes: true
  groups:
    enabled: false

  swagger-ui:
    tags-sorter: alpha
    operationsSorter: alpha
    path: /swagger-ui/index.html